server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://47.106.168.206:3306/xixihaha?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
